// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.support-case-authorization@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SUPPORT_CASE_AUTHORIZATION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SUPPORT_CASE_AUTHORIZATION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_support_case_authorization { () => { "{\"capability_id\":\"lenso.support-case-authorization@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"authorize_case_access\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_support_case_authorization_client { () => { "{\"capability_id\":\"lenso.support-case-authorization@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_support_case_authorization_client { () => { "{\"capability_id\":\"lenso.support-case-authorization@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const AUTHORIZE_CASE_ACCESS_OPERATION: &str = "authorize_case_access";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AuthorizeCaseAccessRequest {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action: AuthorizeCaseAccessRequestAction,
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AuthorizeCaseAccessRequestAction {
    #[serde(rename = "read_public")]
    ReadPublic,
    #[serde(rename = "read_internal")]
    ReadInternal,
    #[serde(rename = "attach_public")]
    AttachPublic,
    #[serde(rename = "attach_internal")]
    AttachInternal,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AuthorizeCaseAccessResponse {
    #[serde(rename = "allowed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub allowed: bool,
    #[serde(rename = "case_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AuthorizeCaseAccessError {
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct SupportCaseAuthorization;
impl RequestCapability for SupportCaseAuthorization {
    type Request = AuthorizeCaseAccessRequest;
    type Response = AuthorizeCaseAccessResponse;
    type DomainError = AuthorizeCaseAccessError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != AUTHORIZE_CASE_ACCESS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportCaseAuthorizationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).authorize_case_access(context, request)
    }
}

impl serde::Serialize for AuthorizeCaseAccessError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AuthorizeCaseAccessError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_authorize_case_access_request(value: &AuthorizeCaseAccessRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_authorize_case_access_request(wire: &str) -> Result<AuthorizeCaseAccessRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_authorize_case_access_response(value: &AuthorizeCaseAccessResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_authorize_case_access_response(wire: &str) -> Result<AuthorizeCaseAccessResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_authorize_case_access_error(value: &AuthorizeCaseAccessError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_authorize_case_access_error(wire: &str) -> Result<AuthorizeCaseAccessError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSupportCaseAuthorizationAuthorizeCaseAccessResult {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError>, RuntimeFailure>;
}
impl __LensoIntoSupportCaseAuthorizationAuthorizeCaseAccessResult for Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportCaseAuthorizationAuthorizeCaseAccessResult for Result<Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportCaseAuthorizationAuthorizeCaseAccessResult for Result<AuthorizeCaseAccessResponse, lenso_plugin_authoring::PluginError<AuthorizeCaseAccessError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportCaseAuthorizationAuthorizeCaseAccessResult for Result<AuthorizeCaseAccessResponse, SupportCaseAuthorizationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AuthorizeCaseAccessResponse, AuthorizeCaseAccessError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportCaseAuthorizationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportCaseAuthorizationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SupportCaseAuthorizationProvider: fmt::Debug + 'static {
    fn authorize_case_access(&self, context: InvocationContext, request: AuthorizeCaseAccessRequest) -> NativeRequestFuture<SupportCaseAuthorization>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_support_case_authorization {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSupportCaseAuthorization;
        impl $crate::SupportCaseAuthorizationProvider for $plugin {
        fn authorize_case_access(&self, context: __LensoNativeSupportSupportCaseAuthorization::InvocationContext, request: $crate::AuthorizeCaseAccessRequest) -> __LensoNativeSupportSupportCaseAuthorization::NativeRequestFuture<$crate::SupportCaseAuthorization> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::authorize_case_access(&plugin, context, request).await;
                $crate::__LensoIntoSupportCaseAuthorizationAuthorizeCaseAccessResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SupportCaseAuthorizationRequestEndpoint { provider: Rc<dyn SupportCaseAuthorizationProvider> }

#[derive(Debug)]
pub struct SupportCaseAuthorizationEndpoint<P: SupportCaseAuthorizationProvider> { provider: Rc<P>, request_endpoint: SupportCaseAuthorizationRequestEndpoint }
impl<P: SupportCaseAuthorizationProvider> SupportCaseAuthorizationEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SupportCaseAuthorizationProvider> = provider.clone();
        Self { provider, request_endpoint: SupportCaseAuthorizationRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SupportCaseAuthorizationProvider> NativeRequestEndpoint for SupportCaseAuthorizationEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        AUTHORIZE_CASE_ACCESS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            AUTHORIZE_CASE_ACCESS_OPERATION => {
                let Ok(request) = request.downcast::<AuthorizeCaseAccessRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).authorize_case_access(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_support_case_authorization {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SupportCaseAuthorizationEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_support_case_authorization {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_support_case_authorization!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SupportCaseAuthorizationClient {
    authorize_case_access: NativeRequestHandle<SupportCaseAuthorization>,
}
impl SupportCaseAuthorizationClient {
    pub fn new(handle: NativeRequestHandle<SupportCaseAuthorization>) -> Self {
        Self { authorize_case_access: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn authorize_case_access(&self, request: AuthorizeCaseAccessRequest) -> Result<AuthorizeCaseAccessResponse, SupportCaseAuthorizationInvocationError> {
        self.authorize_case_access.invoke(AUTHORIZE_CASE_ACCESS_OPERATION, request).await
            .map_err(SupportCaseAuthorizationInvocationError::Runtime)?
            .map_err(SupportCaseAuthorizationInvocationError::Domain)
    }

    pub async fn authorize_case_access_with_context(&self, context: InvocationContext, request: AuthorizeCaseAccessRequest) -> Result<AuthorizeCaseAccessResponse, SupportCaseAuthorizationInvocationError> {
        self.authorize_case_access.invoke_with_context(AUTHORIZE_CASE_ACCESS_OPERATION, context, request).await
            .map_err(SupportCaseAuthorizationInvocationError::Runtime)?
            .map_err(SupportCaseAuthorizationInvocationError::Domain)
    }
}

impl CapabilityClient for SupportCaseAuthorizationClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            authorize_case_access: dependencies.one::<SupportCaseAuthorization>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SupportCaseAuthorizationClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    authorize_case_access: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportCaseAuthorization>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SupportCaseAuthorizationInvocationError {
    Domain(AuthorizeCaseAccessError),
    Runtime(RuntimeFailure),
}
