// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.support-intake@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SUPPORT_INTAKE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SUPPORT_INTAKE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_support_intake { () => { "{\"capability_id\":\"lenso.support-intake@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"append_channel_message\",\"get_requester_case\",\"list_requester_messages\",\"open_case_from_channel\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_support_intake_client { () => { "{\"capability_id\":\"lenso.support-intake@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_support_intake_client { () => { "{\"capability_id\":\"lenso.support-intake@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const APPEND_CHANNEL_MESSAGE_OPERATION: &str = "append_channel_message";
pub const GET_REQUESTER_CASE_OPERATION: &str = "get_requester_case";
pub const LIST_REQUESTER_MESSAGES_OPERATION: &str = "list_requester_messages";
pub const OPEN_CASE_FROM_CHANNEL_OPERATION: &str = "open_case_from_channel";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendChannelMessageRequest {
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendChannelMessageResponse {
    #[serde(rename = "author_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub author_subject: String,
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "case_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_id: String,
    #[serde(rename = "case_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_revision: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppendChannelMessageError {
    CaseNotFound,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequesterCaseRequest {
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequesterCaseResponse {
    #[serde(rename = "case_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "priority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub priority: GetRequesterCaseResponsePriority,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: GetRequesterCaseResponseState,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetRequesterCaseResponsePriority {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "urgent")]
    Urgent,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetRequesterCaseResponseState {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "waiting_customer")]
    WaitingCustomer,
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "closed")]
    Closed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetRequesterCaseError {
    CaseNotFound,
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequesterMessagesRequest {
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequesterMessagesResponse {
    #[serde(rename = "messages")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub messages: Vec<ListRequesterMessagesResponseMessagesItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequesterMessagesResponseMessagesItem {
    #[serde(rename = "author_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub author_subject: String,
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "case_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListRequesterMessagesError {
    CaseNotFound,
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OpenCaseFromChannelRequest {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "priority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub priority: OpenCaseFromChannelRequestPriority,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OpenCaseFromChannelRequestPriority {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "urgent")]
    Urgent,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OpenCaseFromChannelResponse {
    #[serde(rename = "case_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "priority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub priority: OpenCaseFromChannelResponsePriority,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: OpenCaseFromChannelResponseState,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OpenCaseFromChannelResponsePriority {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "urgent")]
    Urgent,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OpenCaseFromChannelResponseState {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "waiting_customer")]
    WaitingCustomer,
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "closed")]
    Closed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum OpenCaseFromChannelError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct SupportIntakeAppendChannelMessage;
impl RequestCapability for SupportIntakeAppendChannelMessage {
    type Request = AppendChannelMessageRequest;
    type Response = AppendChannelMessageResponse;
    type DomainError = AppendChannelMessageError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != APPEND_CHANNEL_MESSAGE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportIntakeRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).append_channel_message(context, request)
    }
}

#[derive(Debug)]
pub struct SupportIntakeGetRequesterCase;
impl RequestCapability for SupportIntakeGetRequesterCase {
    type Request = GetRequesterCaseRequest;
    type Response = GetRequesterCaseResponse;
    type DomainError = GetRequesterCaseError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_REQUESTER_CASE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportIntakeRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_requester_case(context, request)
    }
}

#[derive(Debug)]
pub struct SupportIntakeListRequesterMessages;
impl RequestCapability for SupportIntakeListRequesterMessages {
    type Request = ListRequesterMessagesRequest;
    type Response = ListRequesterMessagesResponse;
    type DomainError = ListRequesterMessagesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_REQUESTER_MESSAGES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportIntakeRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_requester_messages(context, request)
    }
}

#[derive(Debug)]
pub struct SupportIntakeOpenCaseFromChannel;
impl RequestCapability for SupportIntakeOpenCaseFromChannel {
    type Request = OpenCaseFromChannelRequest;
    type Response = OpenCaseFromChannelResponse;
    type DomainError = OpenCaseFromChannelError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != OPEN_CASE_FROM_CHANNEL_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportIntakeRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).open_case_from_channel(context, request)
    }
}

impl serde::Serialize for AppendChannelMessageError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CaseNotFound => serializer.serialize_str("case_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AppendChannelMessageError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "case_not_found" => Ok(Self::CaseNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetRequesterCaseError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CaseNotFound => serializer.serialize_str("case_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetRequesterCaseError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "case_not_found" => Ok(Self::CaseNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListRequesterMessagesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CaseNotFound => serializer.serialize_str("case_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListRequesterMessagesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "case_not_found" => Ok(Self::CaseNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for OpenCaseFromChannelError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for OpenCaseFromChannelError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_append_channel_message_request(value: &AppendChannelMessageRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_channel_message_request(wire: &str) -> Result<AppendChannelMessageRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_channel_message_response(value: &AppendChannelMessageResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_channel_message_response(wire: &str) -> Result<AppendChannelMessageResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_channel_message_error(value: &AppendChannelMessageError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_channel_message_error(wire: &str) -> Result<AppendChannelMessageError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_requester_case_request(value: &GetRequesterCaseRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_requester_case_request(wire: &str) -> Result<GetRequesterCaseRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_requester_case_response(value: &GetRequesterCaseResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_requester_case_response(wire: &str) -> Result<GetRequesterCaseResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_requester_case_error(value: &GetRequesterCaseError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_requester_case_error(wire: &str) -> Result<GetRequesterCaseError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_requester_messages_request(value: &ListRequesterMessagesRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requester_messages_request(wire: &str) -> Result<ListRequesterMessagesRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_requester_messages_response(value: &ListRequesterMessagesResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requester_messages_response(wire: &str) -> Result<ListRequesterMessagesResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_requester_messages_error(value: &ListRequesterMessagesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requester_messages_error(wire: &str) -> Result<ListRequesterMessagesError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_open_case_from_channel_request(value: &OpenCaseFromChannelRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_open_case_from_channel_request(wire: &str) -> Result<OpenCaseFromChannelRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_open_case_from_channel_response(value: &OpenCaseFromChannelResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_open_case_from_channel_response(wire: &str) -> Result<OpenCaseFromChannelResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_open_case_from_channel_error(value: &OpenCaseFromChannelError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_open_case_from_channel_error(wire: &str) -> Result<OpenCaseFromChannelError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSupportIntakeAppendChannelMessageResult {
    fn __lenso_into_result(self) -> Result<Result<AppendChannelMessageResponse, AppendChannelMessageError>, RuntimeFailure>;
}
impl __LensoIntoSupportIntakeAppendChannelMessageResult for Result<AppendChannelMessageResponse, AppendChannelMessageError> {
    fn __lenso_into_result(self) -> Result<Result<AppendChannelMessageResponse, AppendChannelMessageError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportIntakeAppendChannelMessageResult for Result<Result<AppendChannelMessageResponse, AppendChannelMessageError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AppendChannelMessageResponse, AppendChannelMessageError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportIntakeAppendChannelMessageResult for Result<AppendChannelMessageResponse, lenso_plugin_authoring::PluginError<AppendChannelMessageError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AppendChannelMessageResponse, AppendChannelMessageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportIntakeAppendChannelMessageResult for Result<AppendChannelMessageResponse, SupportIntakeAppendChannelMessageInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AppendChannelMessageResponse, AppendChannelMessageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportIntakeAppendChannelMessageInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportIntakeAppendChannelMessageInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSupportIntakeGetRequesterCaseResult {
    fn __lenso_into_result(self) -> Result<Result<GetRequesterCaseResponse, GetRequesterCaseError>, RuntimeFailure>;
}
impl __LensoIntoSupportIntakeGetRequesterCaseResult for Result<GetRequesterCaseResponse, GetRequesterCaseError> {
    fn __lenso_into_result(self) -> Result<Result<GetRequesterCaseResponse, GetRequesterCaseError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportIntakeGetRequesterCaseResult for Result<Result<GetRequesterCaseResponse, GetRequesterCaseError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetRequesterCaseResponse, GetRequesterCaseError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportIntakeGetRequesterCaseResult for Result<GetRequesterCaseResponse, lenso_plugin_authoring::PluginError<GetRequesterCaseError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetRequesterCaseResponse, GetRequesterCaseError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportIntakeGetRequesterCaseResult for Result<GetRequesterCaseResponse, SupportIntakeGetRequesterCaseInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetRequesterCaseResponse, GetRequesterCaseError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportIntakeGetRequesterCaseInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportIntakeGetRequesterCaseInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSupportIntakeListRequesterMessagesResult {
    fn __lenso_into_result(self) -> Result<Result<ListRequesterMessagesResponse, ListRequesterMessagesError>, RuntimeFailure>;
}
impl __LensoIntoSupportIntakeListRequesterMessagesResult for Result<ListRequesterMessagesResponse, ListRequesterMessagesError> {
    fn __lenso_into_result(self) -> Result<Result<ListRequesterMessagesResponse, ListRequesterMessagesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportIntakeListRequesterMessagesResult for Result<Result<ListRequesterMessagesResponse, ListRequesterMessagesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListRequesterMessagesResponse, ListRequesterMessagesError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportIntakeListRequesterMessagesResult for Result<ListRequesterMessagesResponse, lenso_plugin_authoring::PluginError<ListRequesterMessagesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListRequesterMessagesResponse, ListRequesterMessagesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportIntakeListRequesterMessagesResult for Result<ListRequesterMessagesResponse, SupportIntakeListRequesterMessagesInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListRequesterMessagesResponse, ListRequesterMessagesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportIntakeListRequesterMessagesInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportIntakeListRequesterMessagesInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSupportIntakeOpenCaseFromChannelResult {
    fn __lenso_into_result(self) -> Result<Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError>, RuntimeFailure>;
}
impl __LensoIntoSupportIntakeOpenCaseFromChannelResult for Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError> {
    fn __lenso_into_result(self) -> Result<Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportIntakeOpenCaseFromChannelResult for Result<Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportIntakeOpenCaseFromChannelResult for Result<OpenCaseFromChannelResponse, lenso_plugin_authoring::PluginError<OpenCaseFromChannelError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportIntakeOpenCaseFromChannelResult for Result<OpenCaseFromChannelResponse, SupportIntakeOpenCaseFromChannelInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<OpenCaseFromChannelResponse, OpenCaseFromChannelError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportIntakeOpenCaseFromChannelInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportIntakeOpenCaseFromChannelInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SupportIntakeProvider: fmt::Debug + 'static {
    fn append_channel_message(&self, context: InvocationContext, request: AppendChannelMessageRequest) -> NativeRequestFuture<SupportIntakeAppendChannelMessage>;
    fn get_requester_case(&self, context: InvocationContext, request: GetRequesterCaseRequest) -> NativeRequestFuture<SupportIntakeGetRequesterCase>;
    fn list_requester_messages(&self, context: InvocationContext, request: ListRequesterMessagesRequest) -> NativeRequestFuture<SupportIntakeListRequesterMessages>;
    fn open_case_from_channel(&self, context: InvocationContext, request: OpenCaseFromChannelRequest) -> NativeRequestFuture<SupportIntakeOpenCaseFromChannel>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_support_intake {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSupportIntake;
        impl $crate::SupportIntakeProvider for $plugin {
        fn append_channel_message(&self, context: __LensoNativeSupportSupportIntake::InvocationContext, request: $crate::AppendChannelMessageRequest) -> __LensoNativeSupportSupportIntake::NativeRequestFuture<$crate::SupportIntakeAppendChannelMessage> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::append_channel_message(&plugin, context, request).await;
                $crate::__LensoIntoSupportIntakeAppendChannelMessageResult::__lenso_into_result(result)
            })
        }
        fn get_requester_case(&self, context: __LensoNativeSupportSupportIntake::InvocationContext, request: $crate::GetRequesterCaseRequest) -> __LensoNativeSupportSupportIntake::NativeRequestFuture<$crate::SupportIntakeGetRequesterCase> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_requester_case(&plugin, context, request).await;
                $crate::__LensoIntoSupportIntakeGetRequesterCaseResult::__lenso_into_result(result)
            })
        }
        fn list_requester_messages(&self, context: __LensoNativeSupportSupportIntake::InvocationContext, request: $crate::ListRequesterMessagesRequest) -> __LensoNativeSupportSupportIntake::NativeRequestFuture<$crate::SupportIntakeListRequesterMessages> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_requester_messages(&plugin, context, request).await;
                $crate::__LensoIntoSupportIntakeListRequesterMessagesResult::__lenso_into_result(result)
            })
        }
        fn open_case_from_channel(&self, context: __LensoNativeSupportSupportIntake::InvocationContext, request: $crate::OpenCaseFromChannelRequest) -> __LensoNativeSupportSupportIntake::NativeRequestFuture<$crate::SupportIntakeOpenCaseFromChannel> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::open_case_from_channel(&plugin, context, request).await;
                $crate::__LensoIntoSupportIntakeOpenCaseFromChannelResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SupportIntakeRequestEndpoint { provider: Rc<dyn SupportIntakeProvider> }

#[derive(Debug)]
pub struct SupportIntakeEndpoint<P: SupportIntakeProvider> { provider: Rc<P>, request_endpoint: SupportIntakeRequestEndpoint }
impl<P: SupportIntakeProvider> SupportIntakeEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SupportIntakeProvider> = provider.clone();
        Self { provider, request_endpoint: SupportIntakeRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SupportIntakeProvider> NativeRequestEndpoint for SupportIntakeEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        APPEND_CHANNEL_MESSAGE_OPERATION,
        GET_REQUESTER_CASE_OPERATION,
        LIST_REQUESTER_MESSAGES_OPERATION,
        OPEN_CASE_FROM_CHANNEL_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            APPEND_CHANNEL_MESSAGE_OPERATION => {
                let Ok(request) = request.downcast::<AppendChannelMessageRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).append_channel_message(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_REQUESTER_CASE_OPERATION => {
                let Ok(request) = request.downcast::<GetRequesterCaseRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_requester_case(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_REQUESTER_MESSAGES_OPERATION => {
                let Ok(request) = request.downcast::<ListRequesterMessagesRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_requester_messages(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            OPEN_CASE_FROM_CHANNEL_OPERATION => {
                let Ok(request) = request.downcast::<OpenCaseFromChannelRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).open_case_from_channel(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_support_intake {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SupportIntakeEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_support_intake {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_support_intake!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SupportIntakeClient {
    append_channel_message: NativeRequestHandle<SupportIntakeAppendChannelMessage>,
    get_requester_case: NativeRequestHandle<SupportIntakeGetRequesterCase>,
    list_requester_messages: NativeRequestHandle<SupportIntakeListRequesterMessages>,
    open_case_from_channel: NativeRequestHandle<SupportIntakeOpenCaseFromChannel>,
}
impl SupportIntakeClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn append_channel_message(&self, request: AppendChannelMessageRequest) -> Result<AppendChannelMessageResponse, SupportIntakeAppendChannelMessageInvocationError> {
        self.append_channel_message.invoke(APPEND_CHANNEL_MESSAGE_OPERATION, request).await
            .map_err(SupportIntakeAppendChannelMessageInvocationError::Runtime)?
            .map_err(SupportIntakeAppendChannelMessageInvocationError::Domain)
    }

    pub async fn append_channel_message_with_context(&self, context: InvocationContext, request: AppendChannelMessageRequest) -> Result<AppendChannelMessageResponse, SupportIntakeAppendChannelMessageInvocationError> {
        self.append_channel_message.invoke_with_context(APPEND_CHANNEL_MESSAGE_OPERATION, context, request).await
            .map_err(SupportIntakeAppendChannelMessageInvocationError::Runtime)?
            .map_err(SupportIntakeAppendChannelMessageInvocationError::Domain)
    }

    pub async fn get_requester_case(&self, request: GetRequesterCaseRequest) -> Result<GetRequesterCaseResponse, SupportIntakeGetRequesterCaseInvocationError> {
        self.get_requester_case.invoke(GET_REQUESTER_CASE_OPERATION, request).await
            .map_err(SupportIntakeGetRequesterCaseInvocationError::Runtime)?
            .map_err(SupportIntakeGetRequesterCaseInvocationError::Domain)
    }

    pub async fn get_requester_case_with_context(&self, context: InvocationContext, request: GetRequesterCaseRequest) -> Result<GetRequesterCaseResponse, SupportIntakeGetRequesterCaseInvocationError> {
        self.get_requester_case.invoke_with_context(GET_REQUESTER_CASE_OPERATION, context, request).await
            .map_err(SupportIntakeGetRequesterCaseInvocationError::Runtime)?
            .map_err(SupportIntakeGetRequesterCaseInvocationError::Domain)
    }

    pub async fn list_requester_messages(&self, request: ListRequesterMessagesRequest) -> Result<ListRequesterMessagesResponse, SupportIntakeListRequesterMessagesInvocationError> {
        self.list_requester_messages.invoke(LIST_REQUESTER_MESSAGES_OPERATION, request).await
            .map_err(SupportIntakeListRequesterMessagesInvocationError::Runtime)?
            .map_err(SupportIntakeListRequesterMessagesInvocationError::Domain)
    }

    pub async fn list_requester_messages_with_context(&self, context: InvocationContext, request: ListRequesterMessagesRequest) -> Result<ListRequesterMessagesResponse, SupportIntakeListRequesterMessagesInvocationError> {
        self.list_requester_messages.invoke_with_context(LIST_REQUESTER_MESSAGES_OPERATION, context, request).await
            .map_err(SupportIntakeListRequesterMessagesInvocationError::Runtime)?
            .map_err(SupportIntakeListRequesterMessagesInvocationError::Domain)
    }

    pub async fn open_case_from_channel(&self, request: OpenCaseFromChannelRequest) -> Result<OpenCaseFromChannelResponse, SupportIntakeOpenCaseFromChannelInvocationError> {
        self.open_case_from_channel.invoke(OPEN_CASE_FROM_CHANNEL_OPERATION, request).await
            .map_err(SupportIntakeOpenCaseFromChannelInvocationError::Runtime)?
            .map_err(SupportIntakeOpenCaseFromChannelInvocationError::Domain)
    }

    pub async fn open_case_from_channel_with_context(&self, context: InvocationContext, request: OpenCaseFromChannelRequest) -> Result<OpenCaseFromChannelResponse, SupportIntakeOpenCaseFromChannelInvocationError> {
        self.open_case_from_channel.invoke_with_context(OPEN_CASE_FROM_CHANNEL_OPERATION, context, request).await
            .map_err(SupportIntakeOpenCaseFromChannelInvocationError::Runtime)?
            .map_err(SupportIntakeOpenCaseFromChannelInvocationError::Domain)
    }
}

impl CapabilityClient for SupportIntakeClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            append_channel_message: dependencies.one::<SupportIntakeAppendChannelMessage>()?,
            get_requester_case: dependencies.one::<SupportIntakeGetRequesterCase>()?,
            list_requester_messages: dependencies.one::<SupportIntakeListRequesterMessages>()?,
            open_case_from_channel: dependencies.one::<SupportIntakeOpenCaseFromChannel>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SupportIntakeClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    append_channel_message: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportIntakeAppendChannelMessage>()?,
                    get_requester_case: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportIntakeGetRequesterCase>()?,
                    list_requester_messages: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportIntakeListRequesterMessages>()?,
                    open_case_from_channel: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportIntakeOpenCaseFromChannel>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SupportIntakeAppendChannelMessageInvocationError {
    Domain(AppendChannelMessageError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SupportIntakeGetRequesterCaseInvocationError {
    Domain(GetRequesterCaseError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SupportIntakeListRequesterMessagesInvocationError {
    Domain(ListRequesterMessagesError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SupportIntakeOpenCaseFromChannelInvocationError {
    Domain(OpenCaseFromChannelError),
    Runtime(RuntimeFailure),
}
